owner: keydevelops
repo: services

workflowSchedule:
  uptime: "*/5 * * * *"
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 0 * * *"
  summary: "0 0 * * *"

sites:
  - name: Germany Server
    url: http://de.prvkey.ru
    slug: de-server
  - name: FishingBot
    url: https://fishingbot.prvkey.ru
    slug: fishingbot
  - name: Noxveil (prvkey)
    url: https://noxveil.prvkey.ru
    slug: noxveil-prvkey
  - name: Noxveil (kiparis)
    url: https://noxveil.kiparis.fun
    slug: noxveil-kiparis
  - name: Конфигурации VPN
    url: https://cfgx.prvkey.ru
    slug: flclashx-cfg
    expectedStatusCodes:
      - 200
      - 404
  - name: Координатор WTorrent
    url: https://wcoord.prvkey.ru
    slug: wcoord
    maxRedirects: 0
    expectedStatusCodes:
      - 301
      - 302
      - 303
      - 307
      - 308

status-website:
  cname: upptime.prvkey.ru
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: PrivateKey's Uptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/keydevelops/services
